In [3]:
#예제1
symbols = "$*&!@"
codes = []

for symbol in symbols:
  codes.append(ord(symbol))

print(codes)

[36, 42, 38, 33, 64]


In [4]:
#예제2
symbols = "$*&!@"
codes = [ord(symbol) for symbol in symbols]

print(codes)

[36, 42, 38, 33, 64]


In [5]:
#예제3
x = '"!~$$*&!@'
dummy = [ord(x) for x in x]

print(x)
print(dummy)

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [6]:
#예제4
symbols = '"!~$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]

print(beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [8]:
#예제5
symbols = '"!~$$*&!@'
beyond_ascii = list(filter(lambda c: c>64, map(ord, symbols)))

print(beyond_ascii, '\n')

print(f"Map function:\n>>> {map(ord, symbols)}")
print(f"List after map: \n>>> {list(map(ord, symbols))}")

[126] 

Map function:
>>> <map object at 0x7bf97d463730>
List after map: 
>>> [34, 33, 126, 36, 36, 42, 38, 33, 64]


In [12]:
#예제6
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)

for color in colors:
  for size in sizes:
    print((color, size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [14]:
#예제7
symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

(33, 35, 94, 38, 38, 35)


In [16]:
#예제8
olors = ['black', 'white']
size = ['S', 'M', 'L']

for tshirt in ('{} {}'.format(c, s) for s in sizes for c in colors):
  print(tshirt)

black S
white S
black M
white M
black L
white L


In [18]:
#예제9
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'),
                ('BRA', 'CE342567'),
                ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
  print('%s/%s' % passport)
  print('{}/{}'.format(passport[0], passport[1]))
  print(f'{passport[0]}/{passport[1]}')

BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855


In [19]:
#예제10
for counrty, _ in traveler_ids:
  print(counrty)

USA
BRA
ESP


In [21]:
#예제11
lax_coordinates = (33.9425, -118.408056)
latitude, longtitude = lax_coordinates
print(latitude)
print(longtitude)

33.9425
-118.408056


In [22]:
#예제12
a = 10; b = 20
b, a = a, b
print(a, b)

20 10


In [28]:
#예제13
divmod(20, 8)

(2, 4)

In [29]:
t = (20, 8)
divmod(*t)

(2, 4)

In [30]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [32]:
#예제14
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [33]:
#예제15
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [34]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [35]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [37]:
#예제16
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [38]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [39]:
#예제17
metro_areas = [
    ("Tokyo", "JP", 36.933, (35, 139)),
    ("Delhi NCR", "IN", 21, (28, 77)),
    ("Mexico City", "MX", 20, (19, -99)),
    ("New York-Newark", "US", 20, (40, -74)),
    ("Sao Paulo", "BR", 19, (-23, -46))
]

print("{:15} | {:^9} | {:^9}".format('', 'lat.', 'long.'))
fmt = "{:15} | {:^9.4f} | {:^9.4f}"

for name, cc, pop, (lat, longi) in metro_areas:
  if longi <= 0:
    print(fmt.format(name, lat, longi))

                |   lat.    |   long.  
Mexico City     |  19.0000  | -99.0000 
New York-Newark |  40.0000  | -74.0000 
Sao Paulo       | -23.0000  | -46.0000 


In [40]:
#예제18
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689, 139.691))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689, 139.691))

In [41]:
tokyo.population

36.933

In [44]:
tokyo.coordinates

(35.689, 139.691)

In [45]:
tokyo[1]

'JP'

In [47]:
#예제19
City._fields

('name', 'country', 'population', 'coordinates')

In [48]:
LatLong = namedtuple('LatLong', "lat long")
delhi_data = ("Delhi NCR", 'IN', 21.935, LatLong(28.613, 77.208))

In [49]:
delhi = City._make(delhi_data)
delhi._asdict()

{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.613, long=77.208)}

In [50]:
for key, value in delhi._asdict().items():
  print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


In [51]:
#예제20
l = [10, 20, 30, 40, 50, 60]
l[:2]

[10, 20]

In [52]:
l[2:,]

[30, 40, 50, 60]

In [53]:
l[:3]

[10, 20, 30]

In [54]:
l[3:]

[40, 50, 60]

In [56]:
#예제21
invoice = """
0.....6..................25.........33.......40.......
1909  Pimoroni              $17.50      3     $52.50
1489  6mm Tactile           $4.95       2     $9.90
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 25)
UNIT_PRICE = slice(25, 33)
QUANTITY = slice(33, 40)
ITEM_TOTAL = slice(40, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
  print(item[UNIT_PRICE], item[DESCRIPTION])

   $17.5 Pimoroni           
   $4.95 6mm Tactile        
 


In [61]:
#예제22
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [62]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [63]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [64]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [65]:
#예제23
l[2:5] = 100

TypeError: must assign iterable to extended slice

In [66]:
#예제24
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [67]:
#예제25
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [68]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

In [69]:
#예제26
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [71]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [74]:
#예제27
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [75]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [76]:
#예제28
row = ['_'] * 3
board = []
for i in range(3):
  board.append(row)

board[1][2] = 'X'
board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

In [77]:
#예제29
board = []
for i in range(3):
  row = ['_'] * 3
  board.append(row)

print(board)
board[2][0] = 'X'
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [87]:
#예제30
l = [1, 2, 3]
id(l)

136311471223552

In [88]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [89]:
id(l)

136311471223552

In [90]:
#예제31
t = (1, 2, 3)
id(t)

136311471020736

In [91]:
t *= 2
id(t)

136311471845728

In [93]:
#예제32
t = (1, 2, [30, 40])
print(t)

t[2] += [50, 60]

"""
a. t는 (1, 2, [30, 40, 50, 60])이 된다.
b. '튜플 객체는 항목 할당을 지원하지 않는다.'는
    메세지와 함께 TypeError가 발생한다.
c. a와 b 둘 다 틀리다.
d. a와 b 둘 다 맞다.
"""

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [94]:
#예제33
print(t)

(1, 2, [30, 40, 50, 60])


In [95]:
#예제34
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [96]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [97]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [98]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [99]:
#예제35
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [100]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [101]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

In [103]:
#예제36
from array import array
from random import random

floats = array('d', (random() for _ in range(10**7)))
floats[-1]

0.9362693225408224

In [104]:
#예제37
with open('floats.bin', 'wb') as f:
  floats.tofile(f)

In [105]:
floats2 = array('d')

with open('floats.bin', 'rb') as f:
  floats2.fromfile(f, 10**7)

floats2[-1]

0.9362693225408224

In [106]:
floats == floats2

True

In [107]:
#예제38
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [108]:
memv[0]

-2

In [109]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [110]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [111]:
#예제38-1
data = bytearray(b'hello world')
mv = memoryview(data)

print(mv[0])
mv[0] = 72

print(data)

104
bytearray(b'Hello world')


In [112]:
#예제39
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [113]:
type(a)

numpy.ndarray

In [114]:
#예제40
a.shape

(12,)

In [116]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
#예제41
a[2]

array([ 8,  9, 10, 11])

In [122]:
a[2, 1]

np.int64(9)

In [119]:
a[:, 1]

array([1, 5, 9])

In [123]:
#예제42
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])